// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stronaa.Model;

namespace Stronaa.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20200809145747_AlkoholeeeToDb")]
    partial class AlkoholeeeToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Stronaa.Model.Alkohole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KrajPochodzenia")
                        .HasColumnType("int");

                    b.Property<int>("Nazwa")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Alkohole");
                });
#pragma warning restore 612, 618
        }
    }
}
